# Generated by Django 3.2 on 2023-05-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_order',
            field=models.TextField(blank=True, default=''),
        ),
    ]
