# Generated by Django 3.2 on 2023-05-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_custom_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custom_order',
            new_name='message',
        ),
    ]
