# Generated by Django 3.2 on 2023-05-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_custom_order_order_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
