# Generated by Django 3.2 on 2023-05-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orderlineitem_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
