# Generated by Django 3.2 on 2023-03-25 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_quote'),
        ('checkout', '0005_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='price',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='sku',
        ),
        migrations.AddField(
            model_name='quote',
            name='product',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
