# Generated by Django 3.2 on 2023-03-27 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_quote'),
        ('checkout', '0006_auto_20230325_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
