# Generated by Django 3.2 on 2023-04-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_quote_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='product',
        ),
        migrations.AddField(
            model_name='quote',
            name='description',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='name',
            field=models.CharField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='quote',
            name='price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
