# Generated by Django 3.2 on 2023-04-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20230404_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
