# Generated by Django 3.2 on 2023-04-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_quote_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote',
            new_name='Service',
        ),
    ]
