# Generated by Django 3.2 on 2023-04-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_rename_quote_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
