# Generated by Django 3.2 on 2023-05-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=254, null=True)),
                ('lname', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(max_length=600)),
            ],
        ),
    ]
