# Generated by Django 3.2 on 2023-04-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lname',
            field=models.CharField(max_length=254),
        ),
    ]
