# Generated by Django 3.2 on 2023-04-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230405_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='friendly_name',
        ),
    ]
