# Generated by Django 3.2 on 2023-05-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_bagitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='service',
        ),
        migrations.AddField(
            model_name='bag',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
