# Generated by Django 3.2 on 2023-05-02 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0003_auto_20230502_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagitem',
            name='bag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bag.bag'),
        ),
    ]
