# Generated by Django 3.2 on 2023-05-02 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0006_auto_20230502_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitem',
            name='bag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bag.bag'),
        ),
    ]
