# Generated by Django 3.2 on 2023-05-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0007_alter_bagitem_bag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagitem',
            name='bag',
        ),
        migrations.RemoveField(
            model_name='bagitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bagitem',
            name='service',
        ),
        migrations.RemoveField(
            model_name='bagitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bag',
        ),
        migrations.DeleteModel(
            name='BagItem',
        ),
    ]
