# Generated by Django 3.2 on 2023-05-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bag_bagitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagitem',
            name='bag',
        ),
        migrations.RemoveField(
            model_name='bagitem',
            name='service',
        ),
        migrations.DeleteModel(
            name='Bag',
        ),
        migrations.DeleteModel(
            name='BagItem',
        ),
    ]
