# Generated by Django 3.2 on 2023-05-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230507_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
