# Generated by Django 3.2 on 2023-03-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230324_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
