# Generated by Django 3.2 on 2023-05-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.CharField(blank=True, choices=[('25_days', '10.00'), ('20_days', '15.00'), ('15_days', '20.00'), ('10_days', '25.00')], max_length=20, null=True),
        ),
    ]
