# Generated by Django 3.2 on 2023-05-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
    ]
