# Generated by Django 3.2 on 2023-03-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
