# Generated by Django 3.2 on 2023-03-24 15:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_auto_20230324_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('print-publishing', 'print-publishing'), ('website', 'website'), ('illustration', 'illustration'), ('full-package', 'full-package')], max_length=50)),
                ('package', models.CharField(choices=[('bronze', 'bronze'), ('silver', 'silver'), ('gold', 'gold')], max_length=50)),
                ('time_ordered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
