# Generated by Django 3.2 on 2023-03-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='package',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='service',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='time_ordered',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.AddField(
            model_name='quote',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AddField(
            model_name='quote',
            name='description',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='name',
            field=models.CharField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='quote',
            name='price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=6),
        ),
    ]
