# Generated by Django 3.2 on 2023-03-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230325_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
