# Generated by Django 3.2 on 2023-04-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(default=False, max_length=254)),
                ('description', models.TextField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=False, max_digits=6)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
